### ISSUE TITLE
Is it possible to control speed of steps?

### ISSUE THREAD

**Issue by adriangoris** [zhcong/ULN2003-for-ESP32#1]
Thank you very much for uploading this small efficient code. 
It saved me a bit of time. 

Is it possible to control the speed of the motor? 

Is it currently it is sending a step command at the rate of the esp32 clock?

Cheers,
Adrian

**Comment by adriangoris** [comment]
I just realized the "speed" of the motor is set by the delay variable when the stepper is initialized.

It may be more useful to pass the delay as an argument into the step method. It would allow for more granular controls without having to re initialized the stepper each time.

**Comment by zhcong** [comment]
Sorry, I don't know much about embedded devices. I just copy and adjest little from [here](https://github.com/IDWizard/uln2003), 

> Stepper.create(Pin(16,Pin.OUT),Pin(17,Pin.OUT),Pin(5,Pin.OUT),Pin(18,Pin.OUT), delay=2)

And delay is supported.
I invite you to be the creator of this project, verify that your code is working properly and then modify this project.
